name: Auto-merge PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Activer l'auto-merge
        run: gh pr merge --auto --squash --repo "${{ github.repository }}" "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
